public class MetadataComponentDependency {
    @AuraEnabled
    public String MetadataComponentName{get;set;}
    @AuraEnabled
    public String MetadataComponentType{get;set;}
    @AuraEnabled
    public String RefMetadataComponentName{get;set;}
    @AuraEnabled
    public String RefMetadataComponentType{get;set;}
    @AuraEnabled
    public String MetadataComponentId{get;set;}
    @AuraEnabled
    public String RefMetadataComponentId{get;set;}
    
}